name: CI Suite
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env: 
  target: i686-unknown-linux-gnu
  toolchain: stable-i686-unknown-linux-gnu

jobs:
  run_linters:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: $HOME/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm
      - name: Install Tools
        run: |
          pip3 install setuptools
          bash tools/ci/install_node.sh
          bash tools/ci/install_spaceman_dmm.sh dreamchecker
          tools/bootstrap/python -c ''
      - name: Run Linters
        run: |
          bash tools/ci/check_filedirs.sh tgstation.dme
          bash tools/ci/check_changelogs.sh
          find . -name "*.php" -print0 | xargs -0 -n1 php -l
          find . -name "*.json" -not -path "*/node_modules/*" -print0 | xargs -0 python3 ./tools/json_verifier.py
          tgui/bin/tgui --lint
          bash tools/ci/check_grep.sh
          tools/bootstrap/python -m dmi.test
          tools/bootstrap/python -m mapmerge2.dmm_test
          ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1
      - name: Annotate Lints
        uses: yogstation13/DreamAnnotate@v1
        if: always()
        with:
          outputFile: output-annotations.txt

  compile_all_maps:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Compile Maps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond
      - name: Compile All Maps
        run: |
          bash tools/ci/install_byond.sh
          source $HOME/BYOND/byond/bin/byondsetup
          python3 tools/ci/template_dm_generator.py
          tgui/bin/tgui --build
          bash tools/ci/dm.sh -DCIBUILDING -DCITESTING -DALL_MAPS tgstation.dme

  auxmaptick:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Build Auxmaptick
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'Putnam3145/auxmaptick'
          ref: '940575c4f02aac7db5f2dfe89feca83566e1538f'
          path: 'auxmaptick'

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: auxmaptick-registry-${{ hashFiles('auxmaptick/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: auxmaptick-index-${{ hashFiles('auxmaptick/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: auxmaptick/target
          key: auxmaptick-build-target-${{ hashFiles('auxmaptick/Cargo.lock') }}

      - name: Install Ubuntu Deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install build-essential g++-multilib libc6-i386 libstdc++6:i386

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{env.toolchain}}
          target: ${{env.target}}
          override: true

      - name: Build
        run: |
          cargo build --manifest-path auxmaptick/Cargo.toml --target=${{env.target}} --release --verbose
      
      - name: Upload libauxmaptick artifact
        uses: actions/upload-artifact@v2
        with:
          name: libauxmaptick
          path: auxmaptick/target/${{env.target}}/release/libauxmaptick.so
  
  auxmos:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Build Auxmos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'Putnam3145/auxmos'
          ref: '38484ddf475be3c02dc3b2524e4a7cafd9bad391'
          path: 'auxmos'

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: auxmos-registry-${{ hashFiles('auxmos/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: auxmos-index-${{ hashFiles('auxmos/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: auxmos/target
          key: auxmos-build-target-${{ hashFiles('auxmos/Cargo.lock') }}

      - name: Install Ubuntu Deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install build-essential g++-multilib libc6-i386 libstdc++6:i386

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{env.toolchain}}
          target: ${{env.target}}
          override: true

      - name: Build
        run: |
          cargo build --manifest-path auxmos/Cargo.toml --target=${{env.target}} --release --verbose
      
      - name: Upload libauxmos artifact
        uses: actions/upload-artifact@v2
        with:
          name: libauxmos
          path: auxmos/target/${{env.target}}/release/libauxmos.so

  run_all_tests:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Integration Tests
    needs: auxmaptick, auxmos
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond

      - name: Setup database
        run: |
          sudo systemctl start mysql
          mysql -u root -proot -e 'CREATE DATABASE tg_ci;'
          mysql -u root -proot tg_ci < SQL/tgstation_schema.sql
          mysql -u root -proot -e 'CREATE DATABASE tg_ci_prefixed;'
          mysql -u root -proot tg_ci_prefixed < SQL/tgstation_schema_prefixed.sql

      - name: Install bsql
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install libmariadb-client-lgpl-dev:i386
          sudo apt install libmariadbd-dev
          sudo apt install build-essential
          sudo apt install gcc-multilib
          sudo apt install g++-multilib
          sudo apt install gcc-4.8-multilib
          sudo apt install g++-4.8-multilib
          bash tools/ci/build_bsql.sh

      - name: Install rust-g
        run: |
          sudo apt install libssl1.1:i386
          bash tools/ci/install_rust_g.sh

      - name: Download auxmaptick library
        uses: actions/download-artifact@v2
        with:
          name: libauxmaptick

      - name: Download libauxmos library
        uses: actions/download-artifact@v2
        with:
          name: libauxmos

      - name: Compile and run tests
        run: |
          bash tools/ci/install_byond.sh
          source $HOME/BYOND/byond/bin/byondsetup
          tgui/bin/tgui --build
          bash tools/ci/dm.sh -DCIBUILDING tgstation.dme
          bash tools/ci/run_server.sh

  test_windows:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: pwsh tools/ci/build.ps1
      - name: Create artifact
        run: |
          md deploy
          bash tools/deploy.sh ./deploy
      - name: Deploy artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: deploy
